all: iwccla_msy-testing.docx

iwccla_msy-testing.docx: iwccla_msy-testing.md ; pandoc --reference-docx=..\references\template.docx --bibliography=..\references\iwccla.bib iwccla_msy-testing.md -o iwccla_msy-testing.docx